apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
spec:
  selector:
    matchLabels:
      app: flask
  replicas: 1
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: smallcase
          image: 591616226324.dkr.ecr.us-east-1.amazonaws.com/test-eks:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
