apiVersion: v1
kind: Service
metadata:
  name: flask-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "auto-delete=no"
    service.beta.kubernetes.io/aws-load-balancer-extra-security-groups: sg-0d1ba0eea0eb2f9bd
spec:
  type: LoadBalancer
  selector:
    app: flask
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
spec:
  selector:
    matchLabels:
      app: flask
  replicas: 1
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: smallcase
          image: 591616226324.dkr.ecr.us-east-1.amazonaws.com/test-eks:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
